# Generated by Django 5.0.1 on 2025-12-10 22:18

import api.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=500, verbose_name='Dirección')),
                ('rut', models.CharField(help_text='Formato: 12.345.678-9 o 12345678-9', max_length=12, unique=True, validators=[api.validators.validar_rut_chileno], verbose_name='RUT')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Equipo')),
                ('numero_serie', models.CharField(max_length=50, unique=True, validators=[api.validators.validar_numero_serie], verbose_name='Número de Serie')),
                ('critico', models.BooleanField(default=False, verbose_name='¿Es Crítico?')),
                ('fecha_instalacion', models.DateField(verbose_name='Fecha de Instalación')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='api.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['empresa', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlanMantencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Plan')),
                ('frecuencia_dias', models.PositiveIntegerField(help_text='Cada cuántos días se debe realizar la mantención', verbose_name='Frecuencia (días)')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Está Activo?')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_mantencion', to='api.equipo', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Plan de Mantención',
                'verbose_name_plural': 'Planes de Mantención',
                'ordering': ['equipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255, verbose_name='Nombre Completo')),
                ('especialidad', models.CharField(max_length=255, verbose_name='Especialidad')),
                ('telefono', models.CharField(help_text='Formato: +56912345678 o 912345678', max_length=20, validators=[api.validators.validar_telefono_chileno], verbose_name='Teléfono')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tecnico', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Técnico',
                'verbose_name_plural': 'Técnicos',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_programada', models.DateField(verbose_name='Fecha Programada')),
                ('fecha_completada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completación')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_trabajo', to='api.equipo', verbose_name='Equipo')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_trabajo', to='api.planmantencion', verbose_name='Plan de Mantención')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_trabajo', to='api.tecnico', verbose_name='Técnico Asignado')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Órdenes de Trabajo',
                'ordering': ['-fecha_programada'],
            },
        ),
    ]
